
sonar.organization=sprint-rocket-ai
sonar.projectKey=sprint-rocket-ai

# Información del proyecto
sonar.projectName=ms-context-builder
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8

# -----------------------------------------------------------------------------
# CÓDIGO FUENTE
# -----------------------------------------------------------------------------

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes

# -----------------------------------------------------------------------------
# JACOCO
# -----------------------------------------------------------------------------

sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# -----------------------------------------------------------------------------
# EXCLUSIONES DE ANÁLISIS
# -----------------------------------------------------------------------------

sonar.exclusions=\
**/*Application.java,\
**/models/**,\
**/dtos/**,\
**/enums/**,\
**/events/**
