spring.application.name=ms-context-builder
server.port=8080
server.servlet.context-path=/context-builder

# MongoDB
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=${MONGODB_DATABASE}

# AI RestClient
ai-index.client.base-url=${AI_INDEX_BASE_URL}
