spring.application.name=ms-context-builder
server.port=8080
server.servlet.context-path=/context-builder
cors.allowed-origins=${CORS_ALLOWED_ORIGINS}
# MongoDB
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=${MONGODB_DATABASE}

# AI RestClient
ms-ai-engine.base-url=${MS_AI_ENGINE_BASE_URL}
